### ISSUE TITLE
new Client({ apiKey: 'invalidOrWrongKey'}) leads to crash

### ISSUE THREAD

**Issue by prathamesh-majgaonkar** [apivideo/nodejs-sdk#28]
const client = new Client({ apiKey: 'invalidOrWrongKey'});

This has not been handled. The node.js code crashes. Or maybe I am doing something wrong.

**Comment by lutangar** [comment]
Could you share the error message you're getting?
What would be the expected behavior and would you consider submitting a PR?

**Comment by prathamesh-majgaonkar** [comment]
It happens on `dataLiveStream = await client.lives.create('Live Stream', { record });`
Where `client` is `const client = new Client({ apiKey: 'invalidOrWrongKey'});`

```
$PROJECT/node_modules/@api.video/nodejs-sdk/lib/Browser/browser.js:31
            throw new Error('Authentication Failed');
            ^

Error: Authentication Failed
    at Request._callback ($PROJECT/node_modules/@api.video/nodejs-sdk/lib/Browser/browser.js:31:19)
    at Request.self.callback ($PROJECT/node_modules/@api.video/nodejs-sdk/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> ($PROJECT/node_modules/@api.video/nodejs-sdk/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> ($PROJECT/node_modules/@api.video/nodejs-sdk/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
```

**Comment by lutangar** [comment]
This might change in the future (but will involve a breaking change) but this is currently the expected behavior:
```
const client = new Client({ apiKey: 'invalidOrWrongKey'});
const result = await client.lives.create('Live Stream', { record });
```
Ideally what would you expect to get as a `result` of an authentication failure?
What would be the expected behavior?

Anyway in the current client implementation you are supposed to catch the error:
```
const client = new Client({ apiKey: 'invalidOrWrongKey'});
const dataLiveStream = await client.lives.create('Live Stream', { record }).catch(e => {
  // handle Authentication Failed error here
  console.log(e);
});
```
